name: models
description: Models package
version: 0.0.1
homepage:
publish_to: none


environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  flutter_dotenv: 5.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: 2.4.1
  build_runner: 2.4.6
  flutter_gen_runner: 5.3.1
  json_serializable: 6.7.1




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
